main: me.TurtlesAreHot.BendingOnly.Main
name: BendingOnly
version: 1.0.0
description: This plugin only allows you to use bending for combat in a certain world.
author: TurtlesAreHot
api-version: 1.13
commands:
  boreload:
    description: The command to reload the plugin
permissions:
  bo.reload:
    description: Allows you to reload the plugin
    default: op
